CREATE TABLE public.USER (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE public.RECIPE (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    INGREDIENTS TEXT NOT NULL,
    INSTRUCTIONS TEXT NOT NULL,
    IMAGE BYTEA,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_ID SERIAL NOT NULL,
    TAGS VARCHAR(255)[],


    FOREIGN KEY (USER_ID) REFERENCES public.USER(ID) ON DELETE CASCADE
);
