-- Seed data for USER table
DROP TABLE IF EXISTS public.USER CASCADE;

CREATE TABLE public.USER(
    ID SERIAL PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,

    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    CONSTRAINT USER_USERNAME_UNIQUE UNIQUE (USERNAME)
);

DROP TABLE IF EXISTS public.NOTE;

CREATE TABLE public.NOTE(
    ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES public.USER(ID) ON DELETE CASCADE
);



